config/routes.rb
Rails.application.routes.draw do
    root 'planets#index'

    # get "/planets/askljdas", to: "planets#clone" , as: :hello

    resources :planets do
        member do
            get 'copy'
        end
    end
end

app/models/planet.rb
class Planet < ActiveRecord::Base

    validates :name, presence: true

    validates :diameter, numericality: { only_integer: true }

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/planets_controller.rb
class PlanetsController < ApplicationController
    def index
        @planets = Planet.all
    end

    def show
        @planet = Planet.find params[:id]
    end

    def new
        @planet = Planet.new
    end

    def copy
        old = Planet.find params[:id]

        @planet = Planet.new(
            name: old.name,
            diameter: old.diameter
        )

        render :edit
    end

    def create
        binding.pry
        @planet = Planet.create planet_params

        if @planet.valid?
            flash[:notice] = "Your planet has been created."
            redirect_to planets_path
        else
            render :new
        end
    end

    def edit
        @planet = Planet.find params[:id]
    end

    def update
        @planet = Planet.find params[:id]
        @planet.update planet_params

        if @planet.valid?
            flash[:notice] = "Your planet has been updated."

            redirect_to @planet
        else
            render :edit
        end
    end

    def destroy
        @planet = Planet.find params[:id]
        @planet.destroy

        flash[:notice] = "Planet destroyed... you monster!"

        redirect_to planets_path
    end

    private

    def planet_params
        params.require(:planet).permit(
            :name,
            :diameter
        )
    end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

	def index
		render :plain => "welcome to my cool web site"
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!doctype html>
<html>
    <head>
        <title>GalaxyApp</title>
        <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
        <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
        <%= csrf_meta_tags %>
    </head>
    <body>


        <% flash.each do |name, msg| %>
            <%= content_tag :div, msg, class: name %>
        <% end %>

        <%= yield %>

    </body>
</html>

app/views/planets/_form.html.erb
<%= form_for @planet do |f| %>
    <% if @planet.errors.any? %>
        <div id="error_explanation">
            <h3><%= pluralize(@planet.errors.count, "error") %>:</h3>
            <ul>
                <% @planet.errors.full_messages.each do |msg| %>
                    <li><%= msg %></li>
                <% end %>
            </ul>
        </div>
    <% end %>

    <p>
        <%= f.label :name %><br>
        <%= f.text_field :name %>
    </p>

    <p>
        <%= f.label :diameter %><br>
        <%= f.text_field :diameter %>
    </p>

    <p>
        <%= f.submit :class => "btn bnt-lg" %>
    </p>
<% end %>

app/views/planets/edit.html.erb
<% if @planet.new_record? %>
    <h2>Copying <%= @planet.name %></h2>
<% else %>
    <h2>Editing <%= @planet.name %></h2>
<% end %>

<%= link_to 'Back to planet', @planet, class: 'back_link' %>

<%= render 'form' %>

app/views/planets/index.html.erb
<h2>Planets</h2>

<ul>
    <% @planets.each do |planet| %>

        <li>
            <%= link_to planet.name, planet %>
        </li>

    <% end %>
</ul>

<%= link_to 'New planet', new_planet_path %>

app/views/planets/new.html.erb
<h2>Make a planet!</h2>
<%= link_to 'Back to Planets', planets_path, class: 'back_link' %>

<%= render 'form' %>

app/views/planets/show.html.erb
<h2><%= @planet.name %></h2>
<%= link_to 'Back to Planets', planets_path, class: 'back_link' %>

<section class="planet_info">
    <strong>Diameter</strong>: <%= @planet.diameter %>
</section>

<br />

<%= link_to 'Edit', edit_planet_path(@planet) %>
<%= link_to 'Copy', copy_planet_path(@planet) %>
<%= link_to 'Destroy', planet_path(@planet),
            method: :delete,
            data: { confirm: 'Are you sure?' } %>